# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QFlash' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QFlash
  pod "Parse"
  pod "AlamofireImage"

  target 'QFlashTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QFlashUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
